# Pandas

## 数据结构


### Series

In [1]:
from numpy import *
from pandas import *

In [3]:
obj = Series([4,7,-5,3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [8]:
print(obj.index)
print(obj.values)

RangeIndex(start=0, stop=4, step=1)
[ 4  7 -5  3]


In [10]:
obj2 = Series([4,7,-5,3], index=['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [12]:
obj2['a']

-5

Numpy数组运算都会保留索引和值之间的链接

In [14]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [15]:
'b' in obj2

True

In [20]:
#用字典创建Series
sdata = {'Ohio':35000, 'Texas':71000}
obj3 = Series(sdata)
obj3

Ohio     35000
Texas    71000
dtype: int64

缺失值用NaN表示，可以用isnull()和notnull()判断

In [24]:
#在算数运算中会自动对齐不同索引的数据
obj4 = Series({'California':'NaN', 'Ohio': 35000})
obj4 + obj3

California      NaN
Ohio          70000
Texas           NaN
dtype: object

In [26]:
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California      NaN
Ohio          35000
Name: population, dtype: object

In [28]:
obj4.index = ['Bob', 'Cindy']
obj4

Bob        NaN
Cindy    35000
Name: population, dtype: object

### DataFrame

表格型的数据结构，既有行索引也有列索引

In [31]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada'],
       'year': [2000,2001,2002,2001,2002],
       'pop':[1.5,1.7,3.6,2.4,2.9]}
frame = DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [34]:
#指定顺序排列
DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [38]:
#找不到数据生成NaN
DataFrame(data, columns=['year', 'state', 'pop', 'debt'])

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN

In [39]:
#等价于frame['year']
frame.year

0    2000
1    2001
2    2002
3    2001
4    2002
Name: year, dtype: int64

In [42]:
#获取行的值
frame.iloc[0]

state    Ohio
year     2000
pop       1.5
Name: 0, dtype: object

In [44]:
frame['debt'] = 0.5
frame

state  year  pop  debt
0    Ohio  2000  1.5   0.5
1    Ohio  2001  1.7   0.5
2    Ohio  2002  3.6   0.5
3  Nevada  2001  2.4   0.5
4  Nevada  2002  2.9   0.5

In [46]:
frame['debt'] = range(5)
frame

state  year  pop  debt
0    Ohio  2000  1.5     0
1    Ohio  2001  1.7     1
2    Ohio  2002  3.6     2
3  Nevada  2001  2.4     3
4  Nevada  2002  2.9     4

In [56]:
#用Series会精确匹配DataFrame的索引
frame['debt'] = 'NaN'
frame['debt'] = Series([1.2,2.3,2.5], index=[1,3,4])
frame

state  year  pop  debt
0    Ohio  2000  1.5   NaN
1    Ohio  2001  1.7   1.2
2    Ohio  2002  3.6   NaN
3  Nevada  2001  2.4   2.3
4  Nevada  2002  2.9   2.5

In [57]:
del frame['debt']
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [60]:
#传入嵌套字典，则外层字典键作为列，内层键作为行索引
pop = {'Nevada':{2001:2.4, 2002:2.9},
      'Ohio':{2000:1.5, 2001:3.6, 2002:3.6}}
frame3 = DataFrame(pop)
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   3.6
2002     2.9   3.6

In [61]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   3.6   3.6

In [62]:
frame3.values

array([[nan, 1.5],
       [2.4, 3.6],
       [2.9, 3.6]])

Index对象是不可修改的

index = obj.index

方法:append（连接另一个Index） diff（差集）intersection（交集）union（并集）delete(i) insert(i)

## 基本功能

### 重新索引

In [65]:
obj = Series([4.5,7.2,-5.3,3.6], index=['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [67]:
#根据新索引重拍，若不存在则引入缺失值
obj.reindex(['a','b','c','d','e'])

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [69]:
obj.reindex(['a','b','c','d','e'],fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [72]:
#缺失值向前ffill或向后填充bfill
obj3 = Series(['blue', 'purple', 'yellow'], index =[0,2,4])
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

### 丢弃

In [79]:
new_obj = obj.drop('c')
#drop(['b', 'c'])
new_obj

d    4.5
b    7.2
a   -5.3
dtype: float64

### 索引、选取和过滤

#### Series索引

类似于numpy的索引，但不只是整数

['a'] [['a','b']] [1] [2:4] obj[obj < 2]

利用标签的切片运算不同于普通切片，包含末端

#### DataFrame索引
获取一个或多个列

obj[val]:单独一列

obj.ix[val]:单独一行

obj.ix[:, val]:单独一列

obj.ix[val,val2]:行和列

reindex:匹配到新索引

### 运算和数据对齐

In [6]:
#不重叠的索引引入NaN
s1 = Series([7.3,-2.5,3.4,1.5], index=['a','c','d', 'e'])
s2 = Series([-2.1,-2.5,3.6,1.2, 3.1], index=['a','c','e','f', 'g'])
print(s1)
print(s2)
s1+s2

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64
a   -2.1
c   -2.5
e    3.6
f    1.2
g    3.1
dtype: float64


a    5.2
c   -5.0
d    NaN
e    5.1
f    NaN
g    NaN
dtype: float64

对DataFrame，对齐操作发生在行和列上

填充值: 

df1.add(df2, fill_value=0)

重新索引时也可以引入填充值:

df1.reindex(columns=df2.columns, fill_value=0)

### 广播

In [12]:
#DataFrame与Series之间的运算也同理
arr = arange(12).reshape((3,4))
print(arr)
arr- arr[0]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

### 函数应用和映射

numpy的ufun也可用于pandas对象

### 排序和排名

Series对索引进行排序: obj.sort_index() 

对于DataFrame可以对任意轴上的索引进行排序: dp.sort_index()  dp.sort_index(axis=1)

降序: dp.sort_index(axis=1, ascending=False)

Series按值进行排序:

排名(ranking)类似排序，但可以根据某种规则破坏平级关系

In [5]:
#根据在元数据中出现的顺序给出排名
obj = Series([7,-5,7,4,2,0,4])
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [9]:
#降序
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

### 带有重复值的轴索引

In [12]:
obj = Series(range(5), index=['a','a','b','b','c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [16]:
print(obj.index.is_unique)
obj['a']

False


a    0
a    1
dtype: int64

### 汇总和计算描述统计

df.sum()返回含有列小计的Series,NaN会被自动排除

df.sum(axis=1)

df.idxmax()行最大值

count min max argmin argmax(最值的索引位置) idxmin idxmax(最值的索引值) quantile(分位数) sum mean median var std skew kurt cumsum(累积和)

### 相关系数与协方差

obj.corr()协方差矩阵

obj.cov()协方差相关系数

### 唯一值、值计数及成员资格

obj.unique() 唯一值数组

obj.value_counts() 值计数

obj.isin(['b', 'c'])

### 处理缺失数据

string_data.isnull(),内置的None也会被当作NaN处理

Nan处理方法: fillna()用插值方法(fill, bfill)填充缺失数据

dropna()过滤缺失数据，DataFrame默认丢弃任何含缺失值的行

data.dropna(how='all') 只丢弃全为NaN的那些行

df.fillna({1:0.5, 3:-1}) 可以实现对不同列填充不同值, limit参数可以对指定的列操作

## 其他

在pandas中尽量不要使用整数索引，避免歧义

不可以ser[-1]
